apiVersion: v1
kind: Service
metadata:
  name: ecommerce-api
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: ecommerce-api
  ports:
    - port: 4000       # service port
      targetPort: 4000 # pod container port
