apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: dev
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80   # <--- fix here
      nodePort: 30080
