apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: dev
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 3000       # service port
      targetPort: 80   # container port
      nodePort: 30080
